name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]   # main 브랜치에 push될 때 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub 레포지토리 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. JDK 설치 (Spring Boot 빌드용)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Gradle 빌드 실행
      - name: Build with Gradle
        run: ./gradlew build -x test

      # 4. Docker 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Docker 이미지 빌드 & 푸시
      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: kth6417/springboot-app:latest
